context:
  version: "6.6.14"

package:
  name: global
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/global/global-${{ version }}.tar.gz
  sha256: f6e7fd0b68aed292e85bb686616baf6551d5c9424adcddca11d808ba318cb320

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - libtool
    - ncurses
    - sqlite
  run:
    - libltdl
    - universal-ctags

tests:
  - script:
      - global --help

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Source code tag system
  homepage: https://www.gnu.org/software/global
  repository: https://www.gnu.org/software/global

extra:
  recipe-maintainers:
    - danielnachun
